#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/vramesh/Development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/vramesh/Developer/production/sofico/client/mobile/sofico"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/vramesh/Developer/production/sofico/client/mobile/sofico/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "FLUTTER_DEV_DEPENDENCIES_ENABLED=true"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzMuMC0xLjAucHJlLjEyMw==,RkxVVFRFUl9DSEFOTkVMPW1hc3Rlcg==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049ZTI3Mzc3ZWY0ZA==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049ZTI3Mzc3ZWY0ZA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My45LjAgKGJ1aWxkIDMuOS4wLTEzOC4wLmRldik="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/vramesh/Developer/production/sofico/client/mobile/sofico/.dart_tool/package_config.json"
